### ISSUE TITLE
File options ignored

### ISSUE THREAD

**Issue by cmcclure** [sir-dunxalot/ember-cli-sass-lint#1]
All file options seem to be ignored. Even when setting it to include nonsense files, it still uses the sass-lint default glob pattern of `**/*.s+(c|a)ss`. I've tried using the following, but it still tries to lint every `scss` file in the project.

```
files:
  include: '*.asdasdasd'
  ignore:
    - '**/semantic-ui/**/*.scss'
    - '**/auth0-override.scss'
    - '**/login.scss'
    - '**/header.scss'
    - '**/banners.scss'
rules:
  property-sort-order: 0
  ....
```
