### ISSUE TITLE
Linting in addon

### ISSUE THREAD

**Issue by mydea** [sir-dunxalot/ember-cli-sass-lint#3]
I am trying to install ember-cli-sass-lint in an addon with the following simplified folder structure:

```
addon
app
-- styles
    -- my-addon-name
        addon.scss
        _partial1.scss
        _partial2.scss
```

In my (dummy) app's app.scss I then use

`import 'my-addon-name/addon';`

Which works well so far. However, I cannot get the files in app/styles to lint. I tried to include the example config file, slightly adapted:

```
#########################
## Sample Sass Lint File
#########################
# Linter Options
# options:
# File Options
files:
  include: 'app/styles/**/*.scss'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  variable-for-property:
    - 2
    -
      properties:
        - margin
        - content
```

But it is only linting the app.scss file from the dummy app.
